version: '2.4'

services:
  verdaccio:
    image: verdaccio/verdaccio:4.7
    # container_name: npm-mirror-v1
    restart: always
    ports:
      - 4873:4873
    volumes:
      - ./conf/:/verdaccio/conf
      - ./storage/:/verdaccio/storage
    networks:
      - verdaccio

  nginx:
    # build: ./nginx
    image: nginx:1.19.1
    restart: always
    ports:
      - "80:80"
    depends_on:
      - verdaccio
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /www/public
    volumes_from:
      - verdaccio
    networks:
      - verdaccio

networks:
  verdaccio:
    driver: bridge

# volumes:
#   verdaccio:
#     driver: local
